### PR TITLE
Allow installing RPM packages via DNF

### PR DESCRIPTION
**Pull request by hroncok**
- [x] Adapt README

### CODE REVIEW

**Comment by hroncok** [comment]
The test is kinda toothless because it always succeeds, but I've opened https://github.com/fedora-python/fedora-python-tox/pull/33 as well.

**Comment by encukou** [comment]
I can see the DNF installation in the logs.

I would also add a note like in https://github.com/fedora-python/fedora-python-tox/pull/34, but that can go in a different PR.

**Comment by hroncok** [comment]
> but that can go in a different PR

OK.

**Review by encukou — APPROVED** [review]

**Comment by hroncok** [comment]
heh, I forgot where we needed this :D

It was https://github.com/fedora-python/ferrypick/pull/10

**Comment by frenzymadness** [comment]
It works for me as well, thank you! https://github.com/frenzymadness/donors_registry/pull/5

**Pull request merged**
