### PR TITLE
Change Docker image from Lumír's personal one to the fedora-python one

### PR DESCRIPTION
**Pull request by encukou**

### CODE REVIEW

**Comment by frenzymadness** [comment]
Some tests failed here because the new name is not correct.

**Comment by frenzymadness** [comment]
See #10

**Comment by hroncok** [comment]
Sorry for the bad review.

**Comment by encukou** [comment]
Fixed now. Thanks for noticing!

**Comment by hroncok** [comment]
It seems that the CI here tests the current "master" version of this instead of the PR itself, which is confusing.

**Pull request merged**
